{% set name = "ncbi-ab-sample-downloader" %}
{% set version = "0.01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  git_rev: master
  git_url: https://github.com/glwinsor/ncbi-ab-sample-downloader.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - esearch
    - efetch
    - xtract
    - os
    - time
    - re
    - optparse

test:
  imports:
    - ncbi-ab-sample-downloader

about:
  home: https://github.com/glwinsor/antibiograms
  summary: "Download antibiograms from NCBI along with associated SRA or assembly metadata. Also loads this data into the Pseudomonas Genome Database."
  license: MIT
  license_file: LICENSE